<?php
/*
 Cyrocom Wikepage 2006-2 English Language File
 by Sefer Bora LISESIVDIN
*/
$encoding = "iso-8859-1";
$data_dir = "data/en";
$page_default = "Index";
$page_admin = "Admin";
$lang['searchpage'] = "Search page";
$lang['orsearchcontent'] = "or search content";
$lang['search'] = "Search";
$lang['searchingpage'] = "Searching page ";
$lang['searchingcontent'] = "Searching content ";
$lang['oldadminpass'] ="You must enter your old password ";
$lang['adminpass'] = "New Password";
$lang['password'] = "Password";
$lang['changepass'] = "Change Password";
$lang['othersett'] = "Other Settings";
$lang['setpass'] = "Set Password";
$lang['againadminpass'] = "Again New Password (for control) ";
$lang['passless'] = "Page editing without password";
$lang['delfile'] = "Delete file (without ask and return!)";
$lang['delpage'] = "Delete page (without ask and return!)";
$lang['change'] = "Change";
$lang['abbrev_findpage'] = "findpage";
$lang['abbrev_admin'] = "admin";
$lang['abbrev_allpages'] = "allpages";
$lang['abbrev_recentchanges'] = "recentchanges";
$lang['filenotfound'] = " file not found!";
$lang['sorrypagelocked'] = "Sorry, page is locked!";
$lang['cantwriteinpage'] = "Error: can't write in $name (it has $data_perm permissions by $data_owner:$data_group owner:group.) !";
$lang['passmodeerror'] = "Error: Site is personal mode. Content changes can be made with true entered password. You enter wrong password";
$lang['returnhomepage'] = "Back to home page";
$lang['passsuccess'] = "Your password formed successfuly.";
$lang['twononemptypassmustequal'] = "You must enter password at first and two fields must be same.";
$lang['oldpasswrong'] = "You entered your old password wrong.";
$lang['processesok'] = "Processes ok.";
$lang['filloldpass'] = "Please enter old password!";
$lang['twopassmustequal'] = "Two password fields must be same.";
$lang['uploadexists'] = "- File already exists";
$lang['uploadempty'] = "- File size is empty.<br>";
$lang['uploadbig'] = "- File size is too big.<br>";
$lang['uploadnotallowed'] = "- File type isn't allowed.<br>";
$lang['uploaderror'] = "Error trying to upload file:<br>";
$lang['uploadsuccess'] = "Success! The file has been uploaded.";
$lang['uploadlimit'] = "Error! File size might exceed upload limit of server. Try again.";
$lang['edit'] = "Edit ";
$lang['recent'] = "Recent Changes";
$lang['advsearch'] = "Advanced Search ";
$lang['all'] = "All Pages";
$lang['admin'] = "Administration ";
$lang['index'] = "Index ";
$lang['page_recent'] = "Recent_changes";
$lang['page_advsearch'] = "Search";
$lang['page_all'] = "All_pages";
$lang['page_admin'] = "Admin";
$lang['page_index'] = "Index";
$lang['lastupdate'] = "Last Update: ";
$lang['editing'] = "editing ";
$lang['pass'] = "Enter password: ";
$lang['mainmenu'] = "Main Menu ";
$lang['pagecontents'] = "Page Contents ";
$lang['navi'] = "Navigation";
$lang['blogsubject']="Subject";
$lang['blogpage']="Body";
$lang['blog_out']="blog_view";
$lang['blog_input_page']="Blog_Entry";
$lang['copyleft'] = "<p>Permission is granted to copy, distribute and/or modify this document under the terms of the
 GNU Free Documentation License, Version 1.1 or any later version published by the <a href=\"http://www.fsf.org/\">
 Free Software Foundation</a>. If you don't agree please don't add content. </p>
 <small>Powered by mysqlless php wikisite-homepage engine: <a href=\"http://www.cyrocom.com/\">Wikepage</a></small><br/><p></p>";
$lang['writingrules'] = "<ul id=\"footer\" style=\"text-align: left;\"> <small>
						<li>One * before a line puts bullets in front of it </li>
						<li>Links: [Link_type], [http://externallink.com|click] or [http://externallink.com|image.gif] or type URL
						<li>One or more ! make it a headline </li>
						<li>** to make something bold </li>
						<li>__ to underline </li>
						<li>'' to make it italic </li>
						<li>:: :: puts it in a box </li>
						<li> Space at the beginning of a line makes it preformatted </li>
						<li>For tables for every row use ||||column1||column2|||| styling </li>
						<li>For coloring use ##color## written text ## styling. Entered colors used in font tag. Colors are <font color=\"Black\">Black</font>,<font color=\"Silver\"> Silver</font>, <font color=\"Gray\">Gray</font>, 
						<font color=\"Maroon\">Maroon</font>, <font color=\"Red\">Red</font>, <font color=\"Purple\">Purple</font>, 
						<font color=\"Fuchsia\">Fuchsia</font>, <font color=\"Green\">Green</font>, <font color=\"Lime\">Lime</font>, 
						<font color=\"Olive\">Olive</font>, <font color=\"Yellow\">Yellow</font>, <font color=\"Navy\">Navy</font>, 
						<font color=\"Blue\">Blue</font>, <font color=\"Teal\">Teal</font>, <font color=\"Aqua\">Aqua</font> 
						and <font color=\"White\">White</font> of course. Or use RGB codes like <font color=\"#FF9900\">#FF9900</font> or <a href=\"http://www.yourhtmlsource.com/stylesheets/namedcolours.html\" target=\"_blank\">try more</a></li></small>
                      </ul>";

 ?>