<?php
/*
 Cyrocom Wikepage Language Files

 Turkish Language File
 by Sefer Bora LISESIVDIN
 Dec 3, 2004
*/
$encoding = "iso-8859-1";
$data_dir = "data/en";
$page_default = "Index";
$page_admin = "Admin";
$template_show = "show.html";
$template_edit = "edit.html";
$lang_searchpage = "Search page";
$lang_orsearchcontent = "or search content";
$lang_search = "Search";
$lang_searchingpage = "Searching page ";
$lang_searchingcontent = "Searching content ";
$lang_nottochangepass = "If you don't want to change your password, ENTER YOUR PASSWORD IN FIRST FIELD!";
$lang_oldadminpass ="Administration Password";
$lang_adminpass = "New Administration Password";
$lang_againadminpass = "Again New Administration Password (for control)";
$lang_passless = "Page editing without password";
$lang_change = "Change";
$lang_abbrev_findpage = "findpage";
$lang_abbrev_admin = "admin";
$lang_abbrev_allpages = "allpages";
$lang_abbrev_recentchanges = "recentchanges";
$lang_templatenotfound = " template not found!";
$lang_sorrypagelocked = "Sorry, page is locked!";
$lang_cantwriteinpage = "Error: can't write in $name (it has $data_perm permissions by $data_owner:$data_group owner:group.) !";
$lang_passmodeerror = "Error: Site is personal mode. Content changes can be made with true entered password. You enter wrong password";
$lang_returnhomepage = "Back to home page";
$lang_passsuccess = "Your password formed successfuly.";
$lang_twononemptypassmustequal = "You must enter password at first and two fields must be same.";
$lang_oldpasswrong = "You entered your old password wrong.";
$lang_processesok = "Processes ok.";
$lang_twopassmustequal = "Two password fields must be same.";
$lang_writingrules = "<ul id=\"footer\" style=\"text-align: left;\"> <small>
						<li>One * before a line puts bullets in front of it </li>
						<li>Links: [Link_type], [http://externallink.com|click] or [http://externallink.com|image.gif] or type URL
						<li>One or more ! make it a headline </li>
						<li>** to make something bold </li>
						<li>__ to underline </li>
						<li>'' to make it italic </li>
						<li>:: :: puts it in a box </li>
						<li> Space at the beginning of a line makes it preformatted </li>
						<li>For tables for every row use ||||column1||column2|||| styling </li>
						<li>For coloring use ##color## written text ## styling. Entered colors used in font tag. Colors are <font color=\"Black\">Black</font>,<font color=\"Silver\"> Silver</font>, <font color=\"Gray\">Gray</font>, 
						<font color=\"Maroon\">Maroon</font>, <font color=\"Red\">Red</font>, <font color=\"Purple\">Purple</font>, 
						<font color=\"Fuchsia\">Fuchsia</font>, <font color=\"Green\">Green</font>, <font color=\"Lime\">Lime</font>, 
						<font color=\"Olive\">Olive</font>, <font color=\"Yellow\">Yellow</font>, <font color=\"Navy\">Navy</font>, 
						<font color=\"Blue\">Blue</font>, <font color=\"Teal\">Teal</font>, <font color=\"Aqua\">Aqua</font> 
						and <font color=\"White\">White</font> of course. Or use RGB codes like <font color=\"#FF9900\">#FF9900</font> or <a href=\"http://www.yourhtmlsource.com/stylesheets/namedcolours.html\" target=\"_blank\">try more</a></li></small>
                      </ul>";
?>