<?php
/*
 Cyrocom Wikepage 2006-2 Czech Language File
 by Sefer Bora LISESIVDIN
*/
$encoding = "iso-8859-2";
$data_dir = "data/cs";
$page_default = "Index";
$page_admin = "Admin";
$lang['searchpage'] = "Hledání stránky";
$lang['orsearchcontent'] = "nebo hledání obsahu";
$lang['search'] = "Hledat";
$lang['searchingpage'] = "Hledaná stránka ";
$lang['searchingcontent'] = "Hledaný obsah ";
$lang['oldadminpass'] ="Musíte vlo¾it své pùvodní heslo ";
$lang['adminpass'] = "Nové heslo";
$lang['password'] = "Heslo";
$lang['changepass'] = "Zmìna hesla";
$lang['othersett'] = "Ostatní nastavení";
$lang['setpass'] = "Nastavit heslo";
$lang['againadminpass'] = "Nové heslo znovu (pro kontrolu) ";
$lang['passless'] = "Editace stránek bez hesla";
$lang['delfile'] = "Vymazat soubor (bez varování a potvrzení!)";
$lang['delpage'] = "Vymazat stránku (bez varování a potvrzení!)";
$lang['change'] = "Zmìnit";
$lang['abbrev_findpage'] = "findpage";
$lang['abbrev_admin'] = "admin";
$lang['abbrev_allpages'] = "allpages";
$lang['abbrev_recentchanges'] = "recentchanges";
$lang['filenotfound'] = " soubor nenalezen!";
$lang['sorrypagelocked'] = "Stránka je blokovaná!";
$lang['cantwriteinpage'] = "Chyba: nelze zapisovat do $name (má $data_perm oprávnìní pro $data_owner:$data_group owner:group.) !";
$lang['passmodeerror'] = "Chyba: Stránky jsou v osobním módu. Zmìny obsahu lze provádìt po vlo¾ení správného hesla. Vlo¾ené heslo je nesprávné";
$lang['returnhomepage'] = "Zpìt na hlavní stránku";
$lang['passsuccess'] = "Va¹e heslo bylo úspì¹nì zapsáno.";
$lang['twononemptypassmustequal'] = "Musíte vlo¾it nejprve heslo, obì pole musí být shodná.";
$lang['oldpasswrong'] = "Vámi vlo¾ené pùvodní heslo je nesprávné.";
$lang['processesok'] = "Zpracováno OK.";
$lang['filloldpass'] = "Vlo¾te prosím pùvodní heslo!";
$lang['twopassmustequal'] = "Obì hesla musí být shodná.";
$lang['uploadnote'] = "Vyberte soubor pro nahrání:";
$lang['uploadexists'] = "- soubor u¾ existuje";
$lang['uploadempty'] = "- soubor je prázdný.<br />";
$lang['uploadbig'] = "- soubor je pøíli¹ velký.<br />";
$lang['uploadnotallowed'] = "- typ souboru není povolen.<br />";
$lang['uploaderror'] = "Chyba pøi pokusu nahrát soubor:<br />";
$lang['uploadsuccess'] = "Úspìch! Soubor byl nahrán.";
$lang['uploadlimit'] = "Chyba! Velikost souboru zøejmì pøekroèila limit serveru. Zkuste znovu.";
$lang['edit'] = "Editace ";
$lang['recent'] = "Poslední zmìny";
$lang['advsearch'] = "Roz¹íøené hledání ";
$lang['all'] = "V¹echny stránky";
$lang['admin'] = "Administrace ";
$lang['index'] = "Index ";
$lang['page_recent'] = "Poslední_zmìny";
$lang['page_advsearch'] = "Hledání";
$lang['page_all'] = "V¹echny_stránky";
$lang['page_admin'] = "Admin";
$lang['page_index'] = "Index";
$lang['lastupdate'] = "Aktualizováno: ";
$lang['editing'] = "editace ";
$lang['pass'] = "Vlo¾te heslo: ";
$lang['submit'] = "Odeslat";
$lang['mainmenu'] = "Hlavní menu ";
$lang['pagecontents'] = "Obsah stránky ";
$lang['navi'] = "Navigace";
$lang['blogsubject']="Vìc";
$lang['blogpage']="Text";
$lang['blog_out']="blog_view";
$lang['blog_input_page']="Záznam_blogu";
$lang['copyleft'] = "<p>Je povoleno kopírovat, pøedávat a/nebo upravovat tento dokument ve shodì s GNU Free Documentation License, verze 1.1 nebo s kteroukoliv dal¹í verzí, publikovanou <a href=\"http://www.fsf.org/\">
 Free Software Foundation</a>. Nesouhlasíte-li, nemìòte obsah dokumentu. <br />
 <small>Vytvoøeno pomocí bezdatabázové verze php wiki systému: <a href=\"http://www.cyrocom.com/\">Wikepage</a></small><br />";
$lang['writingrules'] = "<ul id=\"footer\" style=\"text-align: left;\"> <small>
						<li>Jedna * pøed øádkem vlo¾í odrá¾ku </li>
						<li>Odkazy: [Link_type], [http://externallink.com|kliknutí] nebo [http://externallink.com|image.gif], nebo vlo¾te URL </li>
						<li>Jeden nebo více ! oznaèí nadpis </li>
						<li>** oznaèí tuèný text </li>
						<li>__ vlo¾í podtr¾ení </li>
						<li>'' oznaèí ¹ikmý text </li>
						<li>:: :: vlo¾í text do boxu </li>
						<li> Mezera na zaèátku øádku znamená pøedformátovaný text </li>
						<li>Tabulka se tvoøí vlo¾ením ||||sloupec1||sloupec2|||| do ka¾dého øádku </li>
						<li>Pro obarvení textu pou¾ijte ##color##...text...##. Vkládejte názvy barev pou¾ívané v tagu font. Barvy jsou <font color=\"Black\">Black</font>,<font color=\"Silver\"> Silver</font>, <font color=\"Gray\">Gray</font>, 
						<font color=\"Maroon\">Maroon</font>, <font color=\"Red\">Red</font>, <font color=\"Purple\">Purple</font>, 
						<font color=\"Fuchsia\">Fuchsia</font>, <font color=\"Green\">Green</font>, <font color=\"Lime\">Lime</font>, 
						<font color=\"Olive\">Olive</font>, <font color=\"Yellow\">Yellow</font>, <font color=\"Navy\">Navy</font>, 
						<font color=\"Blue\">Blue</font>, <font color=\"Teal\">Teal</font>, <font color=\"Aqua\">Aqua</font> 
						a ov¹em <font color=\"Black\">White</font>. Mù¾et pou¾ít RGB kódy jako <font color=\"#FF9900\">#FF9900</font> nebo <a href=\"http://www.yourhtmlsource.com/stylesheets/namedcolours.html\" target=\"_blank\">zkuste dal¹í</a></li></small>
                      </ul>";

 ?>
