<?php
/*
 Cyrocom Wikepage 2006-2 Danish Language File
 by Helmuth Mikkelsen helmuthm@gmail.com
*/
$encoding = "iso-8859-1";
$data_dir = "data/da";
$page_default = "Index";
$page_admin = "Admin";
$lang['searchpage'] = "Søgeside";
$lang['orsearchcontent'] = "eller søgetekst";
$lang['search'] = "Søg";
$lang['searchingpage'] = "Gennemsøg side ";
$lang['searchingcontent'] = "Gennemsøg indhold ";
$lang['oldadminpass'] ="Du skal indtaste dit gamle kodeord ";
$lang['adminpass'] = "Nyt kodeord";
$lang['password'] = "Kodeord";
$lang['changepass'] = "Skift kodeord";
$lang['othersett'] = "Andre indstillinger";
$lang['setpass'] = "Sæt kodeord";
$lang['againadminpass'] = "Kodeord igen (til kontrol) ";
$lang['passless'] = "Sideredigering uden kodeord";
$lang['delfile'] = "Slet fil (uden at blive spurgt!)";
$lang['delpage'] = "Slet side (uden at blive spurgt!)";
$lang['change'] = "Skift";
$lang['abbrev_findpage'] = "findpage";
$lang['abbrev_admin'] = "admin";
$lang['abbrev_allpages'] = "allpages";
$lang['abbrev_recentchanges'] = "recentchanges";
$lang['filenotfound'] = " fil ikke fundet!";
$lang['sorrypagelocked'] = "Desværre, siden er låst!";
$lang['cantwriteinpage'] = "Fejl: kan ikke skrive i $name (den har $data_perm tilladelser af $data_owner:$data_group owner:group.) !";
$lang['passmodeerror'] = "Fejl: Siden er i personlig mode. Ændringer kan foretages efter indtastning af korrekt kodeord. Du indtastede et forkert kodeord";
$lang['returnhomepage'] = "Tilbage til startside";
$lang['passsuccess'] = "Dit kodeord er sat nu.";
$lang['twononemptypassmustequal'] = "Du skal indtaste kodeord først og de to felter skal være identiske.";
$lang['oldpasswrong'] = "Det gamle kodeord er ikke korrekt.";
$lang['processesok'] = "Rettelser gennemført.";
$lang['filloldpass'] = "Indtast venligst gammelt kodeord!";
$lang['twopassmustequal'] = "De to kodeord skal være identiske.";
$lang['uploadexists'] = "- Fil allerede oprettet";
$lang['uploadempty'] = "- Filstørrelse er tom.<br>";
$lang['uploadbig'] = "- Filstørrelse er for stor.<br>";
$lang['uploadnotallowed'] = "- Filtype er ikke tilladt.<br>";
$lang['uploaderror'] = "Fejl under upload af fil:<br>";
$lang['uploadsuccess'] = "Filen er nu uploadet.";
$lang['uploadlimit'] = "Fejl! Filstørrelse overstiger serverens tilladte størrelse. Forsøg igen.";
$lang['edit'] = "Rediger ";
$lang['recent'] = "Seneste ændringer";
$lang['advsearch'] = "Avanceret søgning ";
$lang['all'] = "Alle sider";
$lang['admin'] = "Administration ";
$lang['index'] = "Indeks ";
$lang['page_recent'] = "Seneste_rettelser";
$lang['page_advsearch'] = "Søg";
$lang['page_all'] = "Alle_sider";
$lang['page_admin'] = "Admin";
$lang['page_index'] = "Index";
$lang['lastupdate'] = "Seneste ændring: ";
$lang['editing'] = "redigering ";
$lang['pass'] = "Indtast kodeord: ";
$lang['mainmenu'] = "Hovedmenu ";
$lang['pagecontents'] = "Sideindhold ";
$lang['navi'] = "Navigation";
$lang['blogsubject']="Emne";
$lang['blogpage']="Brødtekst";
$lang['blog_out']="blog_view";
$lang['blog_input_page']="Blog_Entry";
$lang['copyleft'] = "<p>Tilladelse er givet til at kopiere, distribuere og/eller ændre dette dokument under betingelserne i
 GNU Free Documentation License, Version 1.1 eller en senere version offentliggjort af <a href=\"http://www.fsf.org/\">
 Free Software Foundation</a>. Hvis ikke du er indforstået, så undlag venligst at tilføje indhold. </p>
 <small>Powered by mysqlless php wikisite-homepage engine: <a href=\"http://www.cyrocom.com/\">Wikepage</a></small><br/><p></p>";
$lang['writingrules'] = "<ul id=\"footer\" style=\"text-align: left;\"> <small>
						<li>En * foran en linje indsætter bullets foran linjen </li>
						<li>Links: [Link_type], [http://externallink.com|click] eller [http://externallink.com|image.gif] eller indtast URL
						<li>En eller flere ! gør det til en overskrift </li>
						<li>** for at sætte teksten fed </li>
						<li>__ for at understrege </li>
						<li>'' for at sætte i kursiv </li>
						<li>:: :: indsætter i en boks </li>
						<li> Blanktegn (mellemrum) i begyndelsen af en linje sætter den til preformateret </li>
						<li>Til tabeller anvend for hver række ||||column1||column2|||| styling </li>
						<li>Til farver benyt ##color## skrevet tekst ## styling. Indtastede farver benyttet i font tag. Farverne er<font color=\"Black\">Black</font>,<font color=\"Silver\"> Silver</font>, <font color=\"Gray\">Gray</font>, 
						<font color=\"Maroon\">Maroon</font>, <font color=\"Red\">Red</font>, <font color=\"Purple\">Purple</font>, 
						<font color=\"Fuchsia\">Fuchsia</font>, <font color=\"Green\">Green</font>, <font color=\"Lime\">Lime</font>, 
						<font color=\"Olive\">Olive</font>, <font color=\"Yellow\">Yellow</font>, <font color=\"Navy\">Navy</font>, 
						<font color=\"Blue\">Blue</font>, <font color=\"Teal\">Teal</font>, <font color=\"Aqua\">Aqua</font> 
						og <font color=\"White\">White</font> selvfølgelig. Eller anvend RGB-koder som fx <font color=\"#FF9900\">#FF9900</font> eller <a href=\"http://www.yourhtmlsource.com/stylesheets/namedcolours.html\" target=\"_blank\">forsøg flere</a></li></small>
                      </ul>";

 ?>