<?php
/*
 Cyrocom Wikepage 2006-1 German Language File
 by Daniel Schmidt
*/
$encoding = "utf-8";
$data_dir = "data/de";
$page_default = "Index";
$page_admin = "Administration";
$lang['searchpage'] = "Suchseite";
$lang['orsearchcontent'] = "oder Suchtext";
$lang['search'] = "Suchen";
$lang['searchingpage'] = "durchsuche Seite ";
$lang['searchingcontent'] = "durchsuche Content ";
$lang['oldadminpass'] ="Bitte Passwort eingeben ";
$lang['adminpass'] = "neues Passwort";
$lang['password'] = "Passwort";
$lang['changepass'] = "Passwort ändern";
$lang['othersett'] = "Weitere Einstellungen";
$lang['setpass'] = "Passwort setzen";
$lang['againadminpass'] = "neues Passwort bestätigen (zur Kontrolle) ";
$lang['passless'] = "Seiten ohne Passwort bearbeiten";
$lang['delfile'] = "Datei löschen (ohne Nachfrage!)";
$lang['delpage'] = "Seite löschen (ohne Nachfrage!)";
$lang['change'] = "Ändern";
$lang['abbrev_findpage'] = "findeSeite";
$lang['abbrev_admin'] = "admin";
$lang['abbrev_allpages'] = "alleSeiten";
$lang['abbrev_recentchanges'] = "letzteÄnderungen";
$lang['filenotfound'] = " Datei nicht gefunden!";
$lang['sorrypagelocked'] = "Seite ist gesperrt!";
$lang['cantwriteinpage'] = "Fehler: kann nicht in $name schreiben ($data_perm Zugriffsspere durch $data_owner:$data_group owner:group.) !";
$lang['passmodeerror'] = "Fehler: Webseite ist im Privat-Modus. Änderungen am Inhalt können nur mit dem richtigen Passwort durchgeführt werden. Es wurde das falsche Passwort angegeben.";
$lang['returnhomepage'] = "Zurück zur Startseite";
$lang['passsuccess'] = "Das Passwort wurde erfolgreich gesetzt.";
$lang['twononemptypassmustequal'] = "Erst das Passwort eingeben, beide Felder müssen identisch sein.";
$lang['oldpasswrong'] = "Das alte Passwort wurde falsch eingegeben.";
$lang['processesok'] = "Änderung erfolgreich.";
$lang['filloldpass'] = "Bitte Passwort angeben.";
$lang['twopassmustequal'] = "Beide Passwort-Felder müssen identisch sein.";
$lang['uploadexists'] = "- Datei existiert bereits";
$lang['uploadempty'] = "- Dateigröße ist null.<br>";
$lang['uploadbig'] = "- Datei ist zu groß.<br>";
$lang['uploadnotallowed'] = "- Dateityp nicht erlaubt.<br>";
$lang['uploaderror'] = "Fehler beim Versuch die Datei hochzuladen:<br>";
$lang['uploadsuccess'] = "Datei wurde erfolgreich hochgeladen.";
$lang['uploadlimit'] = "Fehler! Dateigröße übersteigt das Upload-Limit des Servers. Bitte nochmals versuchen.";
$lang['edit'] = "Bearbeiten ";
$lang['recent'] = "Letzte Änderungen";
$lang['advsearch'] = "Erweiterte Suche ";
$lang['all'] = "Alle Seiten";
$lang['admin'] = "Administration ";
$lang['index'] = "Index ";
$lang['page_recent'] = "letzte_Aenderungen";
$lang['page_advsearch'] = "Suchen";
$lang['page_all'] = "alle_Seiten";
$lang['page_admin'] = "Admin";
$lang['page_index'] = "Index";
$lang['lastupdate'] = "Letzte Änderung: ";
$lang['editing'] = "bearbeiten ";
$lang['pass'] = "Passwort eingeben: ";
$lang['mainmenu'] = "Hauptmenü ";
$lang['pagecontents'] = "Seiteninhalte ";
$lang['navi'] = "Navigation";
$lang['copyleft'] = "<p>Dieses Dokument steht unter der GNU Free Documentation License, Version 1.1 oder einer späteren Version, welche von der <a href=\"http://www.fsf.org/\">
 Free Software Foundation</a> veröffentlicht wurde. Das Kopieren, Veröffentlichen oder Ändern ist unter Beachtung dieser Bedingungen erlaubt. </p>
 <small>Powered by <a href=\"http://www.cyrocom.com/\">Wikepage</a>, einer php-basierten, ohne MySQL laufenden Homepage-Software.</small><br/><p></p>";
$lang['writingrules'] = "<ul id=\"footer\" style=\"text-align: left;\"> <small>
						<li>Ein * vor der Zeile erstellt eine Liste. </li>
						<li>Links: [Link_type], [http://externallink.com|klick] oder [http://externallink.com|bild.gif] oder URL eingeben </li>
						<li>Ein oder mehr ! erstellt eine Überschrift. </li>
						<li>** um etwas fett zu schreiben. </li>
						<li>__ zum unterstreichen. </li>
						<li>'' um kursiv zu schreiben. </li>
						<li>:: :: erstellt eine Box </li>
						<li> Ein Leerzeichen am Zeilenbeginn rückt ein. </li>
						<li>Tabellen: Jede Zeile so schreiben, ||||Spalte1||Spalte2|||| </li>
						<li>Farben: ##Farbe## zu schreibender Text ##. Mögliche Farben sind <font color=\"Black\">Black (Schwarz)</font>, <font color=\"Silver\">Silver (silber)</font>, <font color=\"Gray\">Gray (grau)</font>, 
						<font color=\"Maroon\">Maroon (rotbraun)</font>, <font color=\"Red\">Red (rot)</font>, <font color=\"Purple\">Purple (violett)</font>, 
						<font color=\"Fuchsia\">Fuchsia (pink)</font>, <font color=\"Green\">Green (grün)</font>, <font color=\"Lime\">Lime (hellgrün)</font>, 
						<font color=\"Olive\">Olive (dunkelgrün)</font>, <font color=\"Yellow\">Yellow (gelb)</font>, <font color=\"Navy\">Navy (dunkelblau)</font>, 
						<font color=\"Blue\">Blue (blau)</font>, <font color=\"Teal\">Teal (mintgrün)</font>, <font color=\"Aqua\">Aqua (hellblau)</font> 
						und <font color=\"White\">White (weiß)</font>. Auch RGB-Farben sind möglich: <font color=\"#FF9900\">#FF9900</font>, ebenso weitere Farben. Siehe auch <a href=\"http://www.yourhtmlsource.com/stylesheets/namedcolours.html\" target=\"_blank\">hier</a>.</li></small>
                      </ul>";

 ?>
