<?php
/*
 Wikepage 2008-1 English Language File
 by Sefer Bora LISESIVDIN
*/
$encoding = "utf-8";
$data_dir = "data/en";
$page_default = "Index";
$page_admin = "Admin";
$lang['searchpage'] = "Search page title";
$lang['orsearchcontent'] = "or search page content";
$lang['search'] = "Search";
$lang['searchingpage'] = "Searching page titles";
$lang['searchingcontent'] = "Searching content ";
$lang['oldadminpass'] ="Current password";
$lang['adminpass'] = "New Password";
$lang['password'] = "Password";
$lang['changepass'] = "Change Password";
$lang['othersett'] = "Other Settings";
$lang['setpass'] = "New Password";
$lang['againadminpass'] = "New Password (again to confirm) ";
$lang['passless'] = "Allow page edit without password";
$lang['delfile'] = "Delete file (warning: does not ask for confirmation!)";
$lang['delpage'] = "Delete page (warning: does not ask for confirmation)";
$lang['change'] = "Change";
$lang['abbrev_findpage'] = "findpage";
$lang['abbrev_admin'] = "admin";
$lang['abbrev_allpages'] = "allpages";
$lang['abbrev_recentchanges'] = "recentchanges";
$lang['filenotfound'] = " file not found!";
$lang['sorrypagelocked'] = "Sorry, page is locked!";
$lang['cantwriteinpage'] = "Error: can't write to $name (it has $data_perm permissions by $data_owner:$data_group owner:group.) !";
$lang['passmodeerror'] = "Error: Incorrect password - site is in personal mode, and content changes can only be made with the correct password.";
$lang['returnhomepage'] = "Back to home page";
$lang['passsuccess'] = "Your password was changed successfully.";
$lang['twononemptypassmustequal'] = "New password must be re-typed in the confirm field.";
$lang['oldpasswrong'] = "Incorrect password.";
$lang['processesok'] = "The operation completed successfully.";
$lang['filloldpass'] = "Please enter current password.";
$lang['twopassmustequal'] = "Both new password fields must match!";
$lang['uploadnote'] = "Select file to upload:";
$lang['uploadexists'] = "- File already exists";
$lang['uploadempty'] = "- File is empty.<br />";
$lang['uploadbig'] = "- File is too big.<br />";
$lang['uploadnotallowed'] = "- File type not permitted.<br />";
$lang['uploaderror'] = "Error attempting to upload file:<br />";
$lang['uploadsuccess'] = "Success! The file has been uploaded.";
$lang['uploadlimit'] = "Error! File size may exceed upload limit of server. Try again.";
$lang['edit'] = "Edit ";
$lang['recent'] = "Recent Changes";
$lang['advsearch'] = "Advanced Search ";
$lang['all'] = "All Pages";
$lang['admin'] = "Administration ";
$lang['index'] = "Index ";
$lang['page_recent'] = "Recent_changes";
$lang['page_advsearch'] = "Search";
$lang['page_all'] = "All_pages";
$lang['page_admin'] = "Admin";
$lang['page_index'] = "Index";
$lang['lastupdate'] = "Last Update: ";
$lang['editing'] = "editing ";
$lang['pass'] = "Enter password: ";
$lang['submit'] = "Submit";
$lang['mainmenu'] = "Main Menu ";
$lang['pagecontents'] = "Page Contents ";
$lang['navi'] = "Navigation";
$lang['blog_out']="blog_view";
$lang['blog_archive']="blog_archive";
$lang['blog_subject']="Subject:";
$lang['blog_page']="Body:";
$lang['blog_input_page']="Blog_Entry";
$lang['activate_TOC']="Activate Table of Contents";
$lang['TOC']="<div id=\"TOC\"><input type =\"button\" value =\"Table of Contents\" onclick =\"toggleTOC()\"></div>";
$lang['nonews']="No News Found";
$lang['xmlerror']="XML error";
$lang['atline']="at line";
$lang['couldnotxml']="could not open XML input";
$lang['couldnotversioninfo']="System can not connect to internet. You can not import RSS and can not control version info.";
$lang['newversion']="There is a new version of Wikepage. Please upgrade.";
$lang['next']="Next";
$lang['prev']="Previous";
$lang['noimage']="No Image...";
$lang['copyleft'] = "<p>Permission is granted to copy, distribute and/or modify this document under the terms of the
 GNU Free Documentation License, Version 1.1 or any later version published by the <a href=\"http://www.fsf.org/\">
 Free Software Foundation</a>. If you don't agree please don't add content. <br />
 <small>Powered by databaseless php wiki-blog-rss reader hybrid engine: <a href=\"http://www.wikepage.org/\">Wikepage</a></small></p>";
$lang['writingrules'] = "<ul id=\"footer\" style=\"text-align: left;\"> <small>
						<li>One * before a line puts bullets in front of it </li>
						<li>Links: [Link_type], [http://externallink.com|click] or [http://externallink.com|image.gif] or type URL. For more read Sandbox</li>
						<li>One or more ! make it a headline </li>
						<li>** to embolden** </li>
						<li>__ to underline__ </li>
						<li>'' to italicize'' </li>
						<li>::places a box around text:: </li>
						<li> Space at the beginning of a line makes it preformatted </li>
						<li>For tables for every row use ||||column1||column2|||| </li>
						<li>For coloring use ##color## written text ## styling. Entered colors used in font tag. Colors are <font color=\"Black\">Black</font>,<font color=\"Silver\"> Silver</font>, <font color=\"Gray\">Gray</font>, 
						<font color=\"Maroon\">Maroon</font>, <font color=\"Red\">Red</font>, <font color=\"Purple\">Purple</font>, 
						<font color=\"Fuchsia\">Fuchsia</font>, <font color=\"Green\">Green</font>, <font color=\"Lime\">Lime</font>, 
						<font color=\"Olive\">Olive</font>, <font color=\"Yellow\">Yellow</font>, <font color=\"Navy\">Navy</font>, 
						<font color=\"Blue\">Blue</font>, <font color=\"Teal\">Teal</font>, <font color=\"Aqua\">Aqua</font> 
						and <font color=\"Black\">White</font> of course. Or use RGB codes like <font color=\"#FF9900\">#FF9900</font> or <a href=\"http://www.yourhtmlsource.com/stylesheets/namedcolours.html\" target=\"_blank\">try more</a></li></small>
                      </ul>";

 ?>
