<?php
/*
 Wikepage 2007-3 Brazilian Portuguese Language File
 by Jose Carlos Medeiros <jose@psabs.com.br>
*/
$encoding = "utf-8";
$data_dir = "data/ptbr";
$page_default = "Index";
$page_admin = "Admin";
$lang['searchpage'] = "Procurar por título";
$lang['orsearchcontent'] = "ou o procurar por conteúdo";
$lang['search'] = "Procurar";
$lang['searchingpage'] = "Procurando páginas";
$lang['searchingcontent'] = "Procurando conteúdos ";
$lang['oldadminpass'] ="Senha atual";
$lang['adminpass'] = "Nova senha";
$lang['password'] = "Senha";
$lang['changepass'] = "Mudar a Senha";
$lang['othersett'] = "Outras Opções";
$lang['setpass'] = "Nova Senha";
$lang['againadminpass'] = "Nova Senha (confirmação)";
$lang['passless'] = "Permitir a edição sem senha";
$lang['delfile'] = "Apagar arquivo (aviso: não sera pedido confirmação!)";
$lang['delpage'] = "Apagar página (aviso: não sera pedido confirmação)";
$lang['change'] = "Alterar";
$lang['abbrev_findpage'] = "findpage";
$lang['abbrev_admin'] = "admin";
$lang['abbrev_allpages'] = "allpages";
$lang['abbrev_recentchanges'] = "recentchanges";
$lang['filenotfound'] = " arquivo não encontrado!";
$lang['sorrypagelocked'] = "Desculpe, a página esta bloqueada!";
$lang['cantwriteinpage'] = "Erro: impossível salvar: $name (permissão $data_perm para o dono:grupo, $data_owner:$data_group.) !";
$lang['passmodeerror'] = "Erro: Senha incorreta - o site está no modo pessoal, e somente com a senha correta será possível fazer alterações no conteúdo.";
$lang['returnhomepage'] = "Voltar para a Home";
$lang['passsuccess'] = "Sua senha foi alterada com sucesso.";
$lang['twononemptypassmustequal'] = "A nova senha deve ser re-digitada no campo de confirmação.";
$lang['oldpasswrong'] = "Senha incorreta.";
$lang['processesok'] = "A operação foi completada com sucesso.";
$lang['filloldpass'] = "Favor preencher com a senha atual.";
$lang['twopassmustequal'] = "Os campos de nova senha devem ser iguais!";
$lang['uploadnote'] = "Selecione o arquivo a ser carregado:";
$lang['uploadexists'] = "- Arquivo ja existe";
$lang['uploadempty'] = "- Arquivo esta vazio.<br />";
$lang['uploadbig'] = "- Arquivo é muito grande.<br />";
$lang['uploadnotallowed'] = "- Tipo de arquivo não permitido.<br />";
$lang['uploaderror'] = "Erro na tentativa de carregar o arquivo:<br />";
$lang['uploadsuccess'] = "Sucesso! O arquivo foi carregado.";
$lang['uploadlimit'] = "Erro! O tamanho do arquivo pode exceder o limite de servidor. Tente novamente.";
$lang['edit'] = "Editar ";
$lang['recent'] = "Alterações Recentes";
$lang['advsearch'] = "Procura Avançada ";
$lang['all'] = "Todas as Páginas";
$lang['admin'] = "Administração ";
$lang['index'] = "Índice ";
$lang['page_recent'] = "Recent_changes";
$lang['page_advsearch'] = "Search";
$lang['page_all'] = "All_pages";
$lang['page_admin'] = "Admin";
$lang['page_index'] = "Index";
$lang['lastupdate'] = "Última Alteração: ";
$lang['editing'] = "editando ";
$lang['pass'] = "Senha: ";
$lang['submit'] = "Enviar";
$lang['mainmenu'] = "Menu Principal ";
$lang['pagecontents'] = "Conteúdo ";
$lang['navi'] = "Navegação";
$lang['blogsubject']="Assunto";
$lang['blogpage']="Corpo";
$lang['blog_out']="blog_view";
$lang['blog_input_page']="Blog_Entry";
$lang['activate_TOC']="Ativar a Lista de Conteúdos";
$lang['TOC']="<input type =\"button\" value =\"Lista de Conteúdos\" onclick =\"toggleTOC()\"><div id=TOC></div>";
$lang['nonews']="Sem Notícias";
$lang['xmlerror']="Erro XML";
$lang['atline']="na linha";
$lang['couldnotxml']="erro ao abrir o XML";
$lang['copyleft'] = "<p>Permission is granted to copy, distribute and/or modify this document under the terms of the
 GNU Free Documentation License, Version 1.1 or any later version published by the <a href=\"http://www.fsf.org/\">
 Free Software Foundation</a>. If you don't agree please don't add content. <br />
 <small>Powered by databaseless php wiki-blog-rss reader hybrid engine: <a href=\"http://www.wikepage.org/\">Wikepage</a></small><br />";
$lang['writingrules'] = "<ul id=\"footer\" style=\"text-align: left;\"> <small>
						<li>One * before a line puts bullets in front of it </li>
						<li>Links: [Link_type], [http://externallink.com|click] or [http://externallink.com|image.gif] or type URL. For more read Sandbox</li>
						<li>One or more ! make it a headline </li>
						<li>** to embolden** </li>
						<li>__ to underline__ </li>
						<li>'' to italicize'' </li>
						<li>::places a box around text:: </li>
						<li> Space at the beginning of a line makes it preformatted </li>
						<li>For tables for every row use ||||column1||column2|||| </li>
						<li>For coloring use ##color## written text ## styling. Entered colors used in font tag. Colors are <font color=\"Black\">Black</font>,<font color=\"Silver\"> Silver</font>, <font color=\"Gray\">Gray</font>, 
						<font color=\"Maroon\">Maroon</font>, <font color=\"Red\">Red</font>, <font color=\"Purple\">Purple</font>, 
						<font color=\"Fuchsia\">Fuchsia</font>, <font color=\"Green\">Green</font>, <font color=\"Lime\">Lime</font>, 
						<font color=\"Olive\">Olive</font>, <font color=\"Yellow\">Yellow</font>, <font color=\"Navy\">Navy</font>, 
						<font color=\"Blue\">Blue</font>, <font color=\"Teal\">Teal</font>, <font color=\"Aqua\">Aqua</font> 
						and <font color=\"Black\">White</font> of course. Or use RGB codes like <font color=\"#FF9900\">#FF9900</font> or <a href=\"http://www.yourhtmlsource.com/stylesheets/namedcolours.html\" target=\"_blank\">try more</a></li></small>
                      </ul>";

?>
