<?php
/*
 Wikepage 2007-2 Thai Language File
 by Assistant Professor Prachid Tinnabutr,www.prachid.com
*/
$encoding = "utf-8";
$data_dir = "data/th";
$page_default = "สารบัญ";
$page_admin = "การจัดการ";
$lang['searchpage'] = "สืบค้นเรื่อง";
$lang['orsearchcontent'] = "หรือสืบค้นหน้าเนื้อหา";
$lang['search'] = "ค้น";
$lang['searchingpage'] = "กำลังค้นหาชื่อหน้า";
$lang['searchingcontent'] = "กำลังค้นหาเนื่อหา ";
$lang['oldadminpass'] ="รหัสผ่านปัจจุบัน";
$lang['adminpass'] = "รหัสผ่านใหม่";
$lang['password'] = "รหัสผ่าน";
$lang['changepass'] = "เปลี่ยนรหัสผ่าน";
$lang['othersett'] = "การตั้งค่าอื่นๆ";
$lang['setpass'] = "รหัสผ่านใหม่";
$lang['againadminpass'] = "รหัสผ่านใหม่ (พิมพ์ให้เหมือนเดิมอีกครั้งเพื่อยืนยัน) ";
$lang['passless'] = "อนุญาตให้แก้ไขหหน้าเนื้อหา โดยไม่ต้องมีรหัสผ่าน";
$lang['delfile'] = "ลบไฟล์ (คำเตือน: โดยไม่ต้องถามอีก!)";
$lang['delpage'] = "ลบหน้า (คำเตือน: โดยไม่ต้องถามอีก!)";
$lang['change'] = "เปลี่ยน";
$lang['abbrev_findpage'] = "ค้นหน้า";
$lang['abbrev_admin'] = "การจัดการ";
$lang['abbrev_allpages'] = "ทุกหน้า";
$lang['abbrev_recentchanges'] = "การเปลี่ยนแปลงใหม่";
$lang['filenotfound'] = " ไม่พบไฟล์!";
$lang['sorrypagelocked'] = "ขออภัย, หน้านี้ห้ามแก้ไข!";
$lang['cantwriteinpage'] = "ผิดพลาด: ไม่สามารถบันทึก $name (it has $data_perm permissions by $data_owner:$data_group owner:group.) !";
$lang['passmodeerror'] = "ผิดพลาด: รหัสผ่านไม่ถูกต้อง - site is in personal mode, and content changes can only be made with the correct password.";
$lang['returnhomepage'] = "กลับไปหน้าแรก";
$lang['passsuccess'] = "ได้เปลี่ยนรหัสผ่านของคุณเรียบร้อยแล้ว";
$lang['twononemptypassmustequal'] = "New password must be re-typed in the confirm field.";
$lang['oldpasswrong'] = "รหัสผ่านไม่ถูกต้อง.";
$lang['processesok'] = "ได้ดำเนินการเรียบร้อยแล้ว.";
$lang['filloldpass'] = "กรุณาใส่รหัสผ่านที่ใช้ปัจจุบัน";
$lang['twopassmustequal'] = "รหัสผ่านที่ตั้งทั้งสองช่องต้องเหมือนกัน!";
$lang['uploadnote'] = "เลือกส่งไฟล์ขึ้นระบบ:";
$lang['uploadexists'] = "- มีไฟล์ชื่อนี้อยู่ก่อนแล้ว";
$lang['uploadempty'] = "- ยังไม่มีไฟล์.<br />";
$lang['uploadbig'] = "- ไฟล์มีขนาดใหญ่เกินที่กำหนด.<br />";
$lang['uploadnotallowed'] = "- เป็นชนิดของไฟล์ที่ระบบไม่อุญาตรับเข้า.<br />";
$lang['uploaderror'] = "เกิดความผิดพลาดในการส่งไฟล์ขึ้น:<br />";
$lang['uploadsuccess'] = "การส่งไฟล์ขึ้นระบบ เสร็จเรียบร้อยแล้ว";
$lang['uploadlimit'] = "ผิดพลาด! ขนาดไฟล์มีขนาดใหญ่เกินที่เครื่องแม่ข่ายกำหนดไว้.ให้แก้ไขแล้วลองใหม่.";
$lang['edit'] = "แก้ไข ";
$lang['recent'] = "การเปลี่ยนแปลง";
$lang['advsearch'] = "สืบค้น";
$lang['all'] = "แสดงทุกหน้า";
$lang['admin'] = "การบริหารจัดการ";
$lang['index'] = "สารบัญ";
$lang['page_recent'] = "การเปลี่ยนแปลงใหม่";
$lang['page_advsearch'] = "ค้น";
$lang['page_all'] = "ทุกหน้า";
$lang['page_admin'] = "การจัดการ";
$lang['page_index'] = "สารบัญ";
$lang['lastupdate'] = "ปรับปรุงล่าสุดเมื่อ: ";
$lang['editing'] = "การแก้ไข ";
$lang['pass'] = "ใส่รหัสผ่าน: ";
$lang['submit'] = "ส่ง";
$lang['mainmenu'] = "เมนูหลัก ";
$lang['pagecontents'] = "หน้าเนื้อหา";
$lang['navi'] = "เมนูเชื่อมโยง";
$lang['blog_out']="อ่านบล๊อก";
$lang['blog_archive']="บล๊อกเรื่องเดิม";
$lang['blog_subject']="เรื่อง:";
$lang['blog_page']="เนื้อหา:";
$lang['blog_input_page']="บล๊อกมาใหม่";
$lang['activate_TOC']="เปิดใช้สารบัญเนื้อหา(TOC)";
$lang['TOC']="<div id=\"TOC\"><input type =\"button\" value =\"Table of Contents\" onclick =\"toggleTOC()\"></div>";
$lang['nonews']="ไม่พบข่าว:เนื้อหา";
$lang['xmlerror']="XML ผิดพลาด";
$lang['atline']="ที่บรรทัด";
$lang['couldnotxml']="ไม่สามารถเปิดไฟล์ XML ที่นำเข้า";
$lang['couldnotversioninfo']="ไม่สามารถเชื่อมต่อระบบอินเตอร์เน็ตได้. จึงไม่สามารถนำเข้าข้อมูล RSS และไม่สามารถจัดการข้อมูลเวอร์ชั่นได้.";
$lang['newversion']="มี Wikepage เวอร์ชั่นใหม่. กรุณาปรับรุ่นได้แล้ว.";
$lang['next']="ต่อไป";
$lang['prev']="ย้อนกลับ";
$lang['noimage']="ไม่มีภาพ...";
$lang['copyleft'] = "<p>อนุญาตให้ทำการคัดสำเนาได้, แจกจ่ายได้ และแก้ไขเอกสารได้ภายใต้สิทธิอนุญาตแบบ
 GNU Free Documentation License, Version 1.1 or any later version published by the <a href=\"http://www.fsf.org/\">
 Free Software Foundation</a>. หากไม่ต้องการ หรือยอมรับ กรุณาอย่าเพิ่มเนื้อหาลงในนี้. <br />
 <small>Powered by databaseless php wiki-blog-rss reader hybrid engine: <a href=\"http://www.wikepage.org/\">Wikepage</a></small></p>";
$lang['writingrules'] = "<ul id=\"footer\" style=\"text-align: left;\"> <small>
						<li>One * before a line puts bullets in front of it </li>
						<li>Links: [Link_type], [http://externallink.com|click] or [http://externallink.com|image.gif] or type URL. For more read Sandbox</li>
						<li>One or more ! make it a headline </li>
						<li>** to embolden** </li>
						<li>__ to underline__ </li>
						<li>'' to italicize'' </li>
						<li>::places a box around text:: </li>
						<li> Space at the beginning of a line makes it preformatted </li>
						<li>For tables for every row use ||||column1||column2|||| </li>
						<li>For coloring use ##color## written text ## styling. Entered colors used in font tag. Colors are <font color=\"Black\">Black</font>,<font color=\"Silver\"> Silver</font>, <font color=\"Gray\">Gray</font>, 
						<font color=\"Maroon\">Maroon</font>, <font color=\"Red\">Red</font>, <font color=\"Purple\">Purple</font>, 
						<font color=\"Fuchsia\">Fuchsia</font>, <font color=\"Green\">Green</font>, <font color=\"Lime\">Lime</font>, 
						<font color=\"Olive\">Olive</font>, <font color=\"Yellow\">Yellow</font>, <font color=\"Navy\">Navy</font>, 
						<font color=\"Blue\">Blue</font>, <font color=\"Teal\">Teal</font>, <font color=\"Aqua\">Aqua</font> 
						and <font color=\"Black\">White</font> of course. Or use RGB codes like <font color=\"#FF9900\">#FF9900</font> or <a href=\"http://www.yourhtmlsource.com/stylesheets/namedcolours.html\" target=\"_blank\">try more</a></li></small>
                      </ul>";

 ?>
