<?php
/*
 Wikepage 2007-1 Dutch Language File
 by YosTea@gmail.com
*/
$encoding = "utf-8";
$data_dir = "data/nl";
$page_default = "Index";
$page_admin = "Admin";
$lang['searchpage'] = "Zoek pagina";
$lang['orsearchcontent'] = "of zoek inhoud";
$lang['search'] = "Zoek";
$lang['searchingpage'] = "Doorzoek pagina's ";
$lang['searchingcontent'] = "Doorzoek inhoud ";
$lang['oldadminpass'] ="Huidig wachtwoord";
$lang['adminpass'] = "Nieuw wachtwoord";
$lang['password'] = "Wachtwoord";
$lang['changepass'] = "Wijzig wachtwoord";
$lang['othersett'] = "Andere instellingen";
$lang['setpass'] = "Nieuw Wachtwoord";
$lang['againadminpass'] = "Nieuw Wachtwoord (bevestig) ";
$lang['passless'] = "Aanpassen van pagina zonder wachtwoord";
$lang['delfile'] = "Verwijder bestand (let op: vraagt niet om bevestiging!)";
$lang['delpage'] = "Verwijder pagina (let op: vraagt niet om bevestiging!)";
$lang['change'] = "Verander";
$lang['abbrev_findpage'] = "zoekpagina";
$lang['abbrev_admin'] = "admin";
$lang['abbrev_allpages'] = "alles";
$lang['abbrev_recentchanges'] = "recentaangepast";
$lang['filenotfound'] = " bestand niet gevonden!";
$lang['sorrypagelocked'] = "Sorry, pagina is geblokkeerd!";
$lang['cantwriteinpage'] = "Fout: schrijven naar $name is mislukt (het heeft $data_perm permissie voor $data_owner:$data_group gebruiker:groep.) !";
$lang['passmodeerror'] = "Fout: Verkeerd wachtwoord - inhoudelijke veranderingen kunnen alleen worden gemaakt met het juiste wachtwoord.";
$lang['returnhomepage'] = "Terug naar homepage";
$lang['passsuccess'] = "Het wachtwoord is aangepast.";
$lang['twononemptypassmustequal'] = "Nieuw wachtwoord moet nogmaals worden ingevoerd.";
$lang['oldpasswrong'] = "Verkeerd wachtwoord.";
$lang['processesok'] = "De handeling is succesvol afgerond.";
$lang['filloldpass'] = "Tik het huidige wachtwoord.";
$lang['twopassmustequal'] = "Beide nieuwe wachtwoorden moeten overeenkomen!";
$lang['uploadnote'] = "Selecteer bestand om te uploaden:";
$lang['uploadexists'] = "- Bestand bestaat al";
$lang['uploadempty'] = "- Bestand is leeg.<br />";
$lang['uploadbig'] = "- Bestand is te groot.<br />";
$lang['uploadnotallowed'] = "- Bestandstype niet toegestaan.<br />";
$lang['uploaderror'] = "Fout bij het uploaden van het bestand:<br />";
$lang['uploadsuccess'] = "Gefeliciteerd! Het bestand is geupload.";
$lang['uploadlimit'] = "Fout! Bestandsgrootte kan groter zijn dan upload limiet van de server. Probeer opnieuw.";
$lang['edit'] = "Bewerk";
$lang['recent'] = "Recent Aangepast";
$lang['advsearch'] = "Zoeken ";
$lang['all'] = "Alle Pagina's";
$lang['admin'] = "Administratie ";
$lang['index'] = "Index ";
$lang['page_recent'] = "Recent_aangepast";
$lang['page_advsearch'] = "Zoek";
$lang['page_all'] = "Alle_paginas";
$lang['page_admin'] = "Admin";
$lang['page_index'] = "Index";
$lang['lastupdate'] = "Laatste Update: ";
$lang['editing'] = "bewerken ";
$lang['pass'] = "Typ wachtwoord: ";
$lang['submit'] = "Zend";
$lang['mainmenu'] = "Hoofd Menu ";
$lang['pagecontents'] = "Pagina Inhoud ";
$lang['navi'] = "Navigatie";
$lang['blogsubject']="Onderwerp";
$lang['blogpage']="Body";
$lang['blog_out']="blog_view";
$lang['blog_input_page']="Blog_Entry";
$lang['activate_TOC']="Activeer Inhoudsopgave";
$lang['TOC']="<input type =\"button\" value =\"Inhoud\" onclick =\"toggleTOC()\"><div id=TOC></div>";
$lang['nonews']="Geen Nieuwtjes Gevonden";
$lang['xmlerror']="XML fout";
$lang['atline']="in regel";
$lang['couldnotxml']="kan XML input niet openen";
$lang['copyleft'] = "<p>Het is mogelijk om dit document te kopieren, ter beschikking te stellen en/of te veranderen volgens de GNU Free Documentation License, Versie 1.1 (of nieuwer) zoals door de <a href=\"http://www.fsf.org/\">Free Software Foundation</a> is gepubliceerd.<br />
 <small>Powered by databaseloze php wiki-blog-rss software: <a href=\"http://www.wikepage.org/\">Wikepage</a></small><br />";
$lang['writingrules'] = "<ul id=\"footer\" style=\"text-align: left;\"> <small>
						<li>Een * aan het begin van de regel geeft een lijst</li>
						<li>Links: [Link_type], [http://externallink.com|click] of [http://externallink.com|image.gif] of een andere URL. Voor meer info lees Sandbox.</li>
						<li>Een of meer ! voor een koptekst </li>
						<li>** vet ** </li>
						<li>__ onderstreept __ </li>
						<li>''italic'' </li>
						<li>::zet tekst in een vak:: </li>
						<li> een spatie aan het begin geeft een citaat </li>
						<li>Voor tabellen gebruik voor elke rij ||||kolom1||kolom2|||| </li>
						<li>Voor kleur gebruik: ##kleur## je_stuk_tekst_in_die_kleur ## Kleur kan hier vervangen worden door: <font color=\"Black\">Black</font>,<font color=\"Silver\"> Silver</font>, <font color=\"Gray\">Gray</font>, 
						<font color=\"Maroon\">Maroon</font>, <font color=\"Red\">Red</font>, <font color=\"Purple\">Purple</font>, 
						<font color=\"Fuchsia\">Fuchsia</font>, <font color=\"Green\">Green</font>, <font color=\"Lime\">Lime</font>, 
						<font color=\"Olive\">Olive</font>, <font color=\"Yellow\">Yellow</font>, <font color=\"Navy\">Navy</font>, 
						<font color=\"Blue\">Blue</font>, <font color=\"Teal\">Teal</font>, <font color=\"Aqua\">Aqua</font> 
						en <font color=\"Black\">White</font>. Je kunt ook gebruik maken van de RGB codes zoals <font color=\"#FF9900\">#FF9900</font> of <a href=\"http://www.yourhtmlsource.com/stylesheets/namedcolours.html\" target=\"_blank\">voor meer</a></li></small>
                      </ul>";

 ?>