<?php
/*
 Cyrocom Wikepage Language Files

 Turkish Language File
 by Sefer Bora LISESIVDIN
 Dec 3, 2004
*/
$encoding = "windows-1254";
$data_dir = "data/tr";
$page_default = "Ana_sayfa";
$page_admin = "Yönetim";
$template_show = "goster.html";
$template_edit = "duzenle.html";
$lang_searchpage = "Sayfa ismi ile arama";
$lang_orsearchcontent = "yada içerikte arama yap";
$lang_search = "Ara";
$lang_searchingpage = "Aranan sayfa:";
$lang_searchingcontent = "Sayfalarda aranan terim:";
$lang_nottochangepass = "Eðer yönetim þifrenizi deðiþtirmek istemiyorsanýz, SADECE ÝLK ALANA ÞÝFRENÝZÝ GÝRÝNÝZ.";
$lang_oldadminpass ="Yönetim Sistemi Þifresi";
$lang_adminpass = "Yeni Yönetim Sistemi Þifresi";
$lang_againadminpass = "Bir daha Yeni Yönetim Sistemi Þifresi (kontrol amaçlý)";
$lang_passless = "Þifresiz sayfa düzenleme";
$lang_change = "Deðiþtir";
$lang_abbrev_findpage = "sayfabul";
$lang_abbrev_admin = "yönetim";
$lang_abbrev_allpages = "tümsayfalar";
$lang_abbrev_recentchanges = "sondeðiþiklikler";
$lang_templatenotfound = ": Þablon bulunamadý!";
$lang_sorrypagelocked = "Üzgünüm, sayfa kilitli!";
$lang_cantwriteinpage = "Hata: $name içine yazýlamýyor ( $data_perm haklarýna sahip ve $data_owner:$data_group tarafýndan sahiplenilmiþ) !";
$lang_passmodeerror = "Hata: Þifreli yazma modundasýnýz ve girdiðiniz þifre hatalý";
$lang_returnhomepage = "Ana Sayfaya Dön";
$lang_passsuccess = "Þifreniz baþarýyla oluþturuldu.";
$lang_twononemptypassmustequal = "Baþlangýç için mutlaka þifre girmelisiniz ve her iki sifre alanýda ayný olmak zorundadýr.";
$lang_oldpasswrong = "Eski Þifrenizi yanlýþ girdiniz.";
$lang_processesok = "Ýþlemleriniz yapýldý";
$lang_filloldpass = "Eski sifre bolumunu doldurunuz!";
$lang_twopassmustequal = "Her iki þifre alanýda ayný olmak zorundadýr";
$lang_writingrules = "<ul id=\"footer\" style=\"text-align: left;\"> <small><small>
                        <li>Satýr öncesi bir * iþareti maddeleme yapar</li>
                        <li>Linkler: [Link_türü], [http://siteismi.com|týklayýn] yada [http://siteismi.com|resim.gif] yada URL girin
                        <li>Bir yada daha fazla ! iþareti baþlýk yapar</li>
                        <li>** iþaret arasýna yazýlanlar <b> koyu </b>olur</li>
                        <li>__ iþareti arasýna yazýlanlar <u>altý çizgili</u> olur</li>
                        <li>'' iþareti arasýna yazýlanlar <i>yatýk</i> olur</li>
                        <li>:: :: iþareti <span style=\"box\">kutu</span> içene konulmasýna yarar</li>
                        <li> Bir satýr baþýna boþlukla baþlamanýz önbiçemli olmasýna yarar</li>
                        <li>Tablo oluþturmak için her satýrda ||||sütun1||sütun22|||| stilini uygulayýn </li>
						<li>Renklendirme için ##renk## yazý buraya ## stilini uygulayýn. Girilen renk deðeri direkt font tag'ýnda yazýldýðýndan ingilizce karþýlýðýný kullanýn.
						Renkler <font color=\"Black\">Black</font>,<font color=\"Silver\"> Silver</font>, <font color=\"Gray\">Gray</font>, 
						<font color=\"Maroon\">Maroon</font>, <font color=\"Red\">Red</font>, <font color=\"Purple\">Purple</font>, 
						<font color=\"Fuchsia\">Fuchsia</font>, <font color=\"Green\">Green</font>, <font color=\"Lime\">Lime</font>, 
						<font color=\"Olive\">Olive</font>, <font color=\"Yellow\">Yellow</font>, <font color=\"Navy\">Navy</font>, 
						<font color=\"Blue\">Blue</font>, <font color=\"Teal\">Teal</font>, <font color=\"Aqua\">Aqua</font> 
						ve <font color=\"White\">White</font>. Yada RGB kodlarýný kullanabilirsiniz: <font color=\"#FF9900\">#FF9900</font> yada <a href=\"http://www.yourhtmlsource.com/stylesheets/namedcolours.html\" target=\"_blank\">dahasýna bakýn</a>.</li></small></small>
                      </ul>";
?>